version: '2'
services:
  staf-api:
    image: java:8-jdk-alpine
    container_name: staf-api
    working_dir: /usr/app
    ports:
      - "6500:8081"
    depends_on:
      - postgres_db
    command: ["java", "-jar", "-Dspring.profiles.active=prod", "application.jar", "tests"]
    volumes:
      - ./tests:/usr/app/tests
      - ./staf-api-0.0.1-SNAPSHOT.jar:/usr/app/application.jar
    networks:
      - staf-network
  staf-frontend:
    build:
      context: .
      dockerfile: front.Dockerfile
    depends_on:
      - staf-api
    image: staf-nginx
    container_name: staf-front
    ports:
      - "8088:80"
    networks:
      - staf-network
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: stafDB
      POSTGRES_PASSWORD: admin
    ports:
      - "54320:5432"
    networks:
      - staf-network
    volumes:
      - postgres_data:/var/lib/postgres
volumes:
  postgres_data:
networks:
  staf-network:
    driver: bridge